add temporary docker file to build container with an updated MoveIt package

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -26,6 +26,9 @@ set -o pipefail
 # Global Variables Declarations
 ################################################################################
 
+IDENTIFY=${IDENTIFY:-0}
+LAUNCHER=${LAUNCHER:-"0"}
+
 ROS_DISTRO=${ROS_DISTRO:-"Unknown ROS distribuiton"}
 IMAGE_TYPE=${IMAGE_TYPE:-"Invalid image"}
 IMAGE_VERSION=${IMAGE_VERSION:-"Unknown image version"}
@@ -40,13 +43,38 @@ OS_VENDOR=${OS_VENDOR:-"Unknow OS vendor"}
 DEBIAN_SUITE=${DEBIAN_SUITE:-"No Debian version set"}
 
 HARDWARE_MODE=${HARDWARE_MODE:-"sim"}
+ROBOT_DRIVE_TYPE=${HARDWARE_MODE:-"sim"}
+ROSLAUNCH_ARGS=${ROSLAUNCH_ARGS:-""}
+LAUNCHER_UI_ARGS=${LAUNCHER_UI_ARGS:-""}
+START_ROBOT_UI=${START_ROBOT_UI:-""}
+GLOBAL_FILES_TO_SOURCE=${GLOBAL_FILES_TO_SOURCE:-""}         # Presumes ':' as file path delimiter
+USER_FILES_TO_SOURCE=${USER_FILES_TO_SOURCE:-""}             # Presumes ':' as file path delimiter
+LOCAL_FILES_TO_SOURCE=${LOCAL_FILES_TO_SOURCE:-""}           # Presumes ':' as file path delimiter
+GLOBAL_FILES_TO_SUBPROCESS=${GLOBAL_FILES_TO_SUBPROCESS:-""} # Presumes ':' as file path delimiter
+USER_FILES_TO_SUBPROCESS=${USER_FILES_TO_SUBPROCESS:-""}     # Presumes ':' as file path delimiter
+LOCAL_FILES_TO_SUBPROCESS=${LOCAL_FILES_TO_SUBPROCESS:-""}   # Presumes ':' as file path delimiter
+XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-""}
 ROS_SETUP=${ROS_SETUP:-"/opt/ros/$ROS_DISTRO/setup.bash"}
+ETC_DIR=${ETC_DIR:-"/etc/pathpilot"}
 DOCKER_CONFIG=${DOCKER_CONFIG:-""}
+RT_CPUS=${RT_CPUS:-""}
+APPARATUS=${APPARATUS:-"true"}
 
 UID=${UID:-}
 GID=${GID:-}
 USER=${USER:-""}
 HOME=${HOME:-""}
+
+# Commands to run at start-up
+# GLOBAL command is run for every user
+# USER command is run only for the main user (for example 'pathpilot' or 'virtualpathpilot')
+# LOCAL command is run only in this ENTRYPOINT scope
+GLOBAL_PREPROCESS_COMMAND=""
+USER_PREPROCESS_COMMAND=""
+LOCAL_PREPROCESS_COMMAND=""
+
+# Command which was passed as a CMD on container spin-up
+EXECUTE_COMMAND=${@:-""}
 
 ################################################################################
 # Maintenance Functions
@@ -108,11 +136,118 @@ identify() {
 }
 
 add_hostname_to_hosts() {
-    echo "127.0.2.1  $HOSTNAME" >>/etc/hosts
+    local hostname="$1"
+    local hosts_file="/etc/hosts"
+
+    echo "127.0.2.1  $hostname" >>${hosts_file}
     local retval="$?"
     if ((retval != 0)); then
-        log_error "Cannot add current hostname $HOSTNAME to /etc/hosts"
+        log_error "Cannot add current hostname $hostname to $hosts_file"
+        return ${retval}
     fi
+
+    log_info "Hostname $hostname added to the $hosts_file file."
+
+    return 0
+}
+
+check_for_file() {
+    local file="$1"
+
+    if ! [[ -e $file ]]; then
+        log_error "File $file does not exists!"
+        return 1
+    fi
+
+    return 0
+}
+
+add_user() {
+    local new_user_name="$1"
+    local new_user_uid="$2"
+    local new_user_gid="$3"
+    local new_user_home="$4"
+
+    # - Remove stale entries (from `docker commit`)
+    sed -i /etc/passwd -e "/^[^:]*:[^:]*:${new_user_uid}:/ d"
+    local retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot delete UID $new_user_uid from /etc/passwd"
+        return ${retval}
+    fi
+
+    sed -i /etc/passwd -e "/^${new_user_name}:/ d"
+    local retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot delete USER $new_user_name from /etc/passwd"
+        return ${retval}
+    fi
+
+    sed -i /etc/shadow -e "/^${new_user_name}:/ d"
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot delete user $new_user_name from /etc/shadow"
+        return ${retval}
+    fi
+
+    sed -i /etc/group -e "/^[^:]*:[^:]*:${new_user_gid}:/ d"
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot delete GID $new_user_gid from /etc/group"
+        return ${retval}
+    fi
+
+    sed -i /etc/group -e "/^${new_user_gid}:/ d"
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot delete GROUP $new_user_name from /etc/group"
+        return ${retval}
+    fi
+
+    sed -i /etc/gshadow -e "/^${new_user_name}:/ d"
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot delete user $new_user_name from /etc/gshadow"
+        return ${retval}
+    fi
+
+    # - (Re)create the user
+    echo "${new_user_name}:x:${new_user_uid}:${new_user_gid}::${new_user_home}:/bin/bash" >>/etc/passwd
+    local retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot write user $new_user_uid with UID $new_user_uid, " \
+            "GID $new_user_gid and HOME $new_user_home to /etc/passwd"
+        return ${retval}
+    fi
+
+    echo "${new_user_name}:*:18488:0:99999:7:::" >>/etc/shadow
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot write user $new_user_name to /etc/shadow"
+        return ${retval}
+    fi
+
+    echo "${new_user_name}:x:${new_user_gid}:" >>/etc/group
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot write user $new_user_name with " \
+            "GID $new_user_gid from /etc/group"
+        return ${retval}
+    fi
+
+    echo "${new_user_name}:*::" >>/etc/gshadow
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Cannot write user $new_user_name to /etc/gshadow"
+        return ${retval}
+    fi
+
+    log_info "New user created:\n" \
+        "  USERNAME           : $new_user_name\n" \
+        "  USER ID            : $new_user_uid\n" \
+        "  USER GROUP ID      : $new_user_gid\n" \
+        "  USER HOME DIRECTORY: $new_user_home"
+
     return ${retval}
 }
 
@@ -133,6 +268,22 @@ add_user_to_groups() {
     return 0
 }
 
+check_user_and_home() {
+    if [[ "$USER" == "" ]]; then
+        log_error "USER environment variable has to be set and not empty!"
+        return 1
+    else
+        check_for_file "$HOME"
+        local retval="$?"
+        if ((retval != 0)); then
+            log_error "Specified HOME directory '$HOME' for USER $USER does not exist!"
+            return 1
+        fi
+    fi
+
+    return 0
+}
+
 set_machinekit_hal_remote() {
     local remote=${1:-"0"}
 
@@ -148,43 +299,76 @@ set_machinekit_hal_remote() {
     return ${retval}
 }
 
-check_for_file() {
-    local file="$1"
+# Ensure ethercat and docker group IDs match device node/socket groups
+fix_gid_for_device() {
+    local device=$1
+    local wanted_group=$2
 
-    if ! [[ -e $file ]]; then
-        log_error "File $file does not exists!"
-        return 1
+    local original_group="$(stat -c %G $device)"
+    local retval="$?"
+
+    if ((retval != 0)); then
+        log_error "Querying for group name of device $device failed!"
+        return ${retval}
+    fi
+
+    if [[ "$original_group" == "$wanted_group" ]]; then
+        log_info "Device $device already has the wanted access group " \
+            "$wanted_group. Nothing to do!"
+        return 0
+    fi
+
+    # Renumber group
+    local original_gid="$(stat -c %g $device)"
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Querying for group ID of device $device failed!"
+        return ${retval}
+    fi
+
+    if [[ "$original_group" != "UNKNOWN" ]]; then
+        # Conflict; find free GID and renumber other group
+        for FREEGID in $(seq 99); do
+            result=$(getent group $FREEGID) >&/dev/null || true
+            test "${result}" != "" || break
+        done
+        log_info "$device:  Renumbering conflicting group owner $original_group" \
+            "from $original_gid to $FREEGID"
+        sed -i "s/^\([^:]*:[^:]*:\)${original_gid}\(:[^:]*\)\$/\1${FREEGID}\2/" \
+            /etc/group
+        retval="$?"
+        if ((retval != 0)); then
+            log_error "Renumbering conflicting group owner $original_group failed!"
+            return ${retval}
+        fi
+    fi
+    log_info "$device:  Renumbering $wanted_group GID to $original_gid"
+    sed -i "s/^${wanted_group}:x:[0-9]*:\([^:]*\)\$/${wanted_group}:x:${original_gid}:\1/" \
+        /etc/group
+    retval="$?"
+    if ((retval != 0)); then
+        log_error "Renumbering $wanted_group GID to $original_gid failed!"
+        return ${retval}
     fi
 
     return 0
 }
 
-check_for_root_permission() {
-    local current_uid="$(id -u)"
-    local current_gid="$(id -g)"
-
-    if ((current_uid == 0 && current_gid == 0)); then
-        return 0
-    fi
-    log_error "Not running as the Root, but as UID $current_uid and GID " \
-        "$current_gid. This is not possible!"
-    return 1
+check_drive_type() {
+    log_info "HARDWARE_MODE=$HARDWARE_MODE"
+    test "$HARDWARE_MODE" != sim || return 0
+    check_for_file /dev/EtherCAT0 || failure "No /dev/EtherCAT0 device found"
+    test "$(ethercat slaves | wc -l)" -gt 0 || failure "No EtherCAT slaves found"
+    case "$(ethercat slaves -p 0 2>/dev/null | awk '{print $5}')" in
+    SV660_*) ROBOT_DRIVE_TYPE="SV660N" ;;
+    IS620N_*) ROBOT_DRIVE_TYPE="IS620N" ;;
+    *) failure "Unknown drive type" ;;
+    esac
+    log_info "ROBOT_DRIVE_TYPE=$ROBOT_DRIVE_TYPE"
+    export ROBOT_DRIVE_TYPE
+    fix_gid_for_device /dev/EtherCAT0 ethercat
 }
 
-check_for_uid_gid() {
-    local re="^[1-9][0-9]{0,}$"
-
-    if [[ "$UID" =~ $re && "$GID" =~ $re ]]; then
-        return 0
-    fi
-
-    if [[ "$UID" == "0" && "$GID" == "" ]]; then
-        return 1
-    fi
-
-    log_error "Passed only UID or only GID, this is illegal configuration!"
-    return 2
-}
 
 trim_array() {
     local value="$3"
@@ -207,8 +391,42 @@ trim_space() {
     return 0
 }
 
+#add_file_to_local_source_list()
+#add_file_to_user_source_list()
+add_file_to_global_source_list() {
+    local file="$1"
+
+    if [[ "$GLOBAL_FILES_TO_SOURCE" != "" ]]; then
+        GLOBAL_FILES_TO_SOURCE+=","
+
+    fi
+
+    GLOBAL_FILES_TO_SOURCE+="$file"
+
+    return 0
+}
+
+export_variable_for_all() {
+    local variable="$1"
+    local value="$2"
+
+    local command_string="export ${variable}=${value};"$'\n'
+
+    GLOBAL_PREPROCESS_COMMAND+="$command_string"
+}
+
+export_variable_for_user() {
+    local variable="$1"
+    local value="$2"
+
+    local command_string="export ${variable}=${value};"$'\n'
+
+    USER_PREPROCESS_COMMAND+="$command_string"
+}
+
 source_files_command() {
     local input_list="$1"
+    local target_variable="$2"
 
     local -a array
     readarray -c1 -C 'trim_array array' -td: <<<"$input_list"
@@ -218,7 +436,36 @@ source_files_command() {
         return ${retval}
     fi
 
-    USER_COMMAND+="set +o nounset;"$'\n'
+    local item=""
+    for element in "${array[@]}"; do
+        check_for_file "$element"
+        retval="$?"
+        if ((retval != 0)); then
+            log_error "Skipping file $element!"
+            continue
+        else
+            log_info "Adding file $element to the list to source."
+        fi
+
+        item+="source $element;"$'\n'
+    done
+
+    read -r -d '' $target_variable <<<"${!target_variable}"$'\n'"set +o nounset"$'\n'"${item}set -o nounset;"
+
+    return 0
+}
+
+subprocess_files_command() {
+    local input_list="$1"
+    local target_variable="$2"
+
+    local -a array
+    readarray -c1 -C 'trim_array array' -td: <<<"$input_list"
+    local retval="$?"
+    if ((retval != 0)); then
+        log_error "Could not read the input into list"
+        return ${retval}
+    fi
 
     local item=""
     for element in "${array[@]}"; do
@@ -227,16 +474,133 @@ source_files_command() {
         if ((retval != 0)); then
             log_error "Skipping file $element!"
             continue
+        else
+            log_info "Adding file $element to the list to subprocess."
         fi
-        read -r -d '' item <<-EOM
-    source $element;
-EOM
-        USER_COMMAND+="$item"$'\n'
+
+        item+="bash -f $element;"$'\n'
     done
 
-    USER_COMMAND+="set -o nounset;"
+    read -r -d '' $target_variable <<<"${!target_variable}"$'\n'"set +o nounset"$'\n'"${item}set -o nounset;"
 
     return 0
+}
+
+check_for_uid_gid() {
+    local re="^[1-9][0-9]{0,}$"
+
+    if [[ "$UID" =~ $re && "$GID" =~ $re ]]; then
+        return 0
+    fi
+
+    if [[ "$UID" == "0" && "$GID" == "" ]]; then
+        return 1
+    fi
+
+    log_error "Passed only UID or only GID, this is illegal configuration!"
+    return 2
+}
+
+check_for_root_permission() {
+    local current_uid="$(id -u)"
+    local current_gid="$(id -g)"
+
+    if ((current_uid == 0 && current_gid == 0)); then
+        return 0
+    fi
+    log_error "Not running as the Root, but as UID $current_uid and GID " \
+        "$current_gid. This is not possible!"
+    return 1
+}
+
+process_files_to_source() {
+    local retval="0"
+
+    if [[ "$GLOBAL_FILES_TO_SOURCE" != "" ]]; then
+        source_files_command "$GLOBAL_FILES_TO_SOURCE" "GLOBAL_PREPROCESS_COMMAND"
+        retval=$((retval + $?))
+    else
+        log_info "No files to globally source were found."
+    fi
+
+    if [[ "$USER_FILES_TO_SOURCE" != "" ]]; then
+        source_files_command "$USER_FILES_TO_SOURCE" "USER_PREPROCESS_COMMAND"
+        retval=$((retval + $?))
+    else
+        log_info "No files to source for given user were found."
+    fi
+
+    if [[ "$LOCAL_FILES_TO_SOURCE" != "" ]]; then
+        source_files_command "$LOCAL_FILES_TO_SOURCE" "LOCAL_PREPROCESS_COMMAND"
+        retval=$((retval + $?))
+    else
+        log_info "No files to locally source were found."
+    fi
+
+    return ${retval}
+}
+
+process_files_to_subprocess() {
+    local retval="0"
+
+    if [[ "$GLOBAL_FILES_TO_SUBPROCESS" != "" ]]; then
+        subprocess_files_command "$GLOBAL_FILES_TO_SUBPROCESS" "GLOBAL_PREPROCESS_COMMAND"
+        retval=$((retval + $?))
+    else
+        log_info "No files to subprocess were found."
+    fi
+
+    if [[ "$USER_FILES_TO_SUBPROCESS" != "" ]]; then
+        subprocess_files_command "$USER_FILES_TO_SUBPROCESS" "USER_PREPROCESS_COMMAND"
+        retval=$((retval + $?))
+    else
+        log_info "No files to subprocess were found."
+    fi
+
+    if [[ "$LOCAL_FILES_TO_SUBPROCESS" != "" ]]; then
+        subprocess_files_command "$LOCAL_FILES_TO_SUBPROCESS" "LOCAL_PREPROCESS_COMMAND"
+        retval=$((retval + $?))
+    else
+        log_info "No files to subprocess were found."
+    fi
+
+    return ${retval}
+}
+
+finalize_preprocess_commands() {
+    local user="$1"
+    local global_profile_file="/etc/bash.bashrc"
+    local retval="0"
+
+    process_files_to_source
+    retval=$((retval + $?))
+
+    process_files_to_subprocess
+    retval=$((retval + $?))
+
+    if [[ "$GLOBAL_PREPROCESS_COMMAND" != "" ]]; then
+        printf "$GLOBAL_PREPROCESS_COMMAND\n\n" >>${global_profile_file}
+        retval=$((retval + $?))
+
+        log_info "Adding a global command to $global_profile_file"
+    fi
+
+    if [[ "$USER_PREPROCESS_COMMAND" != "" ]]; then
+        # Do not add the user specific command to the ~/.bashrc file as would be
+        # logical for most applications as that files is shared for all TPPR runs.
+        # The $global_profile_file is modified at each TPPR start from clean state
+        read -r -d '' conditioned_command <<-EOM
+if [[ "\$USER" == \"$user\" ]]; then
+$USER_PREPROCESS_COMMAND
+fi
+EOM
+        printf "$conditioned_command\n\n" >>${global_profile_file}
+        retval=$((retval + $?))
+
+        log_info "Adding a user command to $global_profile_file"
+    fi
+
+    return ${retval}
 }
 
 run_pathpilot_robot_command() {
@@ -244,14 +608,19 @@ run_pathpilot_robot_command() {
     local run_command="$2"
 
     sudo -u ${target_user} -E bash -c "
-        eval \"${USER_COMMAND}\"
+        eval \"${GLOBAL_PREPROCESS_COMMAND}\"
+        eval \"${USER_PREPROCESS_COMMAND}\"
+        eval \"${LOCAL_PREPROCESS_COMMAND}\"
         exec ${run_command}
     "
 
     local retval="$?"
     if ((retval != 0)); then
         log_error "Trying to exec custom command \n'$run_command'\n under" \
-            "user $target_user with additional command \n'$USER_COMMAND'\n" \
+            "user $target_user with additional commands:" \
+            "\n'GLOBAL_PREPROCESS_COMMAND: $GLOBAL_PREPROCESS_COMMAND'\n" \
+            "\n'USER_PREPROCESS_COMMAND: $USER_PREPROCESS_COMMAND'\n" \
+            "\n'LOCAL_PREPROCESS_COMMAND: $LOCAL_PREPROCESS_COMMAND'\n" \
             "failed with ERROR CODE $retval"
     fi
     return ${retval}
@@ -262,6 +631,11 @@ run_pathpilot_robot_command() {
 ################################################################################
 
 _main() {
+    # We were asked to identify the image
+    if [[ "$IDENTIFY" == "1" ]]; then
+        identify
+    fi
+
     local retval="-1"
 
     # Check we are root and if not exit out
@@ -271,40 +645,104 @@ _main() {
         failure
     fi
 
-    local pathpilot_uid="$(id -u ${PPRUSER})"
-    local pathpilot_gid="$(id -g ${PPRUSER})"
-
-    export USER="$PPRUSER"
-    export HOME="/home/$USER"
     export FLAVOR="posix"         # Explicitly state we want vanilla Linux Machinekit-HAL
 
-    log_info "Running under UID $pathpilot_uid and GID $pathpilot_gid" \
+    check_for_uid_gid
+    retval="$?"
+    if ((retval == 0)); then
+        check_user_and_home
+        retval="$?"
+        if ((retval != 0)); then
+            failure
+        fi
 
-    add_user_to_groups "$USER" "${user_groups[@]}"
+        log_info "Requested run under specified user UID $UID and GID $GID." \
+            "Creating new user."
+
+        add_user "$USER" "$UID" "$GID" "$HOME"
+        retval="$?"
+        if ((retval != 0)); then
+            failure
+        fi
+    else
+        USER="$PPRUSER"
+        HOME="/home/$PPRUSER"
+
+        export ${USER} ${HOME}
+    fi
+
+    local -a base_user_groups=(plugdev robotusers)
+
+    check_for_file "/var/run/docker.sock"
+    retval="$?"
+    if ((retval == 0)); then
+        retval="$?"
+        fix_gid_for_device "/var/run/docker.sock" "docker"
+        if ((retval != 0)); then
+            failure
+        fi
+
+        base_user_groups+=("docker")
+    else
+        log_error "Docker socket in container is hard requirement!"
+        failure
+    fi
+
+    add_user_to_groups "$USER" "${base_user_groups[@]}"
     retval="$?"
     if ((retval != 0)); then
         failure
     fi
 
-    add_hostname_to_hosts
+    add_hostname_to_hosts "$HOSTNAME"
     retval="$?"
     if ((retval != 0)); then
         failure
     fi
 
-    # Turn off Machinekit-HAL mDNS announcements; dbus socket not bind-mounted
+    add_file_to_global_source_list "$ROS_SETUP"
+    retval="$?"
+    if ((retval != 0)); then
+        failure
+    fi
+
+    # for now we exit, TODO: launch hardware interface and controllers
+    if [[ "$LAUNCHER" == "1" ]]; then
+        log_warning "Launcher run requested." \
+            " The launcher is not currently implemented."
+        finalize_preprocess_commands "$USER"
+        retval="$?"
+        if ((retval != 0)); then
+            failure
+        fi
+
+        ## run execution of ros through supervisord
+        ##run_pathpilot_robot_supervisord "$USER" "$ETC_DIR" "$run_dir"
+
+        # The end of the line
+        retval="$?"
+        if ((retval != 0)); then
+            failure
+        fi
+        success
+    fi
+
+     # Turn off Machinekit-HAL mDNS announcements; dbus socket not bind-mounted
     set_machinekit_hal_remote "0"
     retval="$?"
     if ((retval != 0)); then
         failure
     fi
 
-    source_files_command "$ROS_SETUP" # make ROS accessible in this script
+    finalize_preprocess_commands "$USER"
+    retval="$?"
+    if ((retval != 0)); then
+        failure
+    fi
     
     # ======== TEMPORARY
     export ROS_MASTER_URI=http://127.0.0.1:11311
     export ROS_IP=127.0.0.1
-    source "$ROS_SETUP" 
     # ==========
 
     # Everything else in the books
@@ -319,6 +757,7 @@ _main() {
     fi
     success
 }
+
 ################################################################################
 # Start of execution
 ################################################################################
